services:
  payment_gateway:
    container_name: payment-gateway
    build: .
    ports:
      - "50052:50051"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  payment_gate_db:
    image: postgres:13
    restart: always
    tty: true
    volumes:
      - ../.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=payment_gateway
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - payment_gate_db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
